In [2]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
G = np.array([
    [2,5,2],
    [3,1,4],
    [2,4,5]
])

T = np.array([
    [5],
    [3],
    [4]
])

G_inv = np.linalg.inv(G)
print(G_inv @ T)

[[ 0.91891892]
 [ 0.67567568]
 [-0.10810811]]


In [4]:
G_inv1 = np.linalg.solve(G, T)
print(G_inv1)

[[ 0.91891892]
 [ 0.67567568]
 [-0.10810811]]


In [5]:
A = np.array([
    [1,2,2],
    [5,5,3],
    [1,2,3]
])

B = np.array([
    [5],
    [5],
    [5]
])

A_inv = np.linalg.inv(A)
print(A_inv @ B)

[[-3.]
 [ 4.]
 [ 0.]]


In [6]:
A_inv1 = np.linalg.solve(A, B)
print(A_inv1)

[[-3.]
 [ 4.]
 [ 0.]]
