In [5]:
import numpy as np 
import matplotlib.pyplot as plt
%matplotlib inline

## Transposition

In [6]:
X = np.array([
    [2 ,1, 3],
    [1, 2, 3],
    [1, -2, 1]
])
X

array([[ 2,  1,  3],
       [ 1,  2,  3],
       [ 1, -2,  1]])

In [7]:
XT1 = np.transpose(X)

In [8]:
XT2 = X.T

In [9]:
np.array_equiv(XT1, XT2)

True

In [10]:
Y = np.array([
    [1,1,-3,2],
    [2,1,-2,3],
])
Y.shape

(2, 4)

In [11]:
np.transpose(Y).shape

(4, 2)

In [12]:
Y.T.shape

(4, 2)

## Dot Product/Inner Product

In [13]:
X = np.array([
    [2,1],
    [3,2]
])
Y = np.array([
    [0,1],
    [2,3]
])

In [14]:
np.dot(X,Y)

array([[2, 5],
       [4, 9]])

In [15]:
X.dot(Y)

array([[2, 5],
       [4, 9]])

In [16]:
X @ Y 

array([[2, 5],
       [4, 9]])

In [17]:
np.matmul(X,Y)

array([[2, 5],
       [4, 9]])

## Rule 1 The inner dimensions of the two matrices in question must be the same.

In [21]:
G = np.array([
    [1,2],
    [2,3],
    [1,1]
])
T = np.array([
    [3,3],
    [0,1],
    [1,3]
])
A = np.array([
    [2,3,2],
    [3,2,3]
])
print(G.shape)
print(T.shape)
print(A.shape)

(3, 2)
(3, 2)
(2, 3)


In [22]:
G @ A

array([[ 8,  7,  8],
       [13, 12, 13],
       [ 5,  5,  5]])

In [23]:
T @ A

array([[15, 15, 15],
       [ 3,  2,  3],
       [11,  9, 11]])

In [24]:
G @ T.T

array([[ 9,  2,  7],
       [15,  3, 11],
       [ 6,  1,  4]])

In [25]:
X = np.array([
    [2,1,1,3]
])
Y = np.array([
    [-1,3,2,-3]
])
print(X.shape)
print(Y.shape)

(1, 4)
(1, 4)


In [26]:
Y.T @ X

array([[-2, -1, -1, -3],
       [ 6,  3,  3,  9],
       [ 4,  2,  2,  6],
       [-6, -3, -3, -9]])

## Rule 2: Dot Product has special properties

In [28]:
G = np.array([
    [1,1,3],
    [2,-2,3],
    [1,1,1]
])
T = np.array([
    [2,-2,3],
    [-2,-3,2],
    [2,1,3]
])
A = np.array([
    [-1,3,1],
    [2,3,3],
    [1,2,3]
])

In [29]:
G.dot(np.zeros(G.shape))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [30]:
z_mat = np.zeros(G.shape)
z_mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [31]:
a_dot_z = G.dot(np.zeros(G.shape))
a_dot_z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [32]:
np.array_equal(a_dot_z,z_mat)

True

In [33]:
null_mat = np.empty(G.shape, dtype=float)
null = np.array(null_mat,dtype=float)
print(null)
np.allclose(a_dot_z,null)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


True

## Determinant

In [34]:
X = np.array([
    [2,3],
    [1,2]
])
np.linalg.det(X)

1.0

In [35]:
Y = np.array([
    [1,1,3,3],
    [2,-1,1,2],
    [-2,-1,-3,2],
    [1,1,2,2]
])
np.linalg.det(Y)

-15.999999999999998

## Inverse

In [41]:
X = np.array([
    [1,2],
    [2,3]
])

np.array(X @ np.linalg.inv(X), dtype=int)

array([[1, 0],
       [0, 1]])

In [47]:
Y = np.array([
    [1,3,2,3,3,2,3],
    [0,2,0,3,2,3,2],
    [2,2,1,0,1,0,3],
    [1,2,2,3,2,3,1],
    [1,2,1,3,1,1,1],
    [-3,3,1,2,0,3,-3],
    [-2,-3,1,3,1,2,1],
])
Y_inv = np.linalg.inv(Y)
np.array(Y @ Y_inv,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1]])

In [48]:
squad = np.array([
    [1.0, 1.0, 0.5],
    [0.7, 0.7, 0.9],
    [0.3, 0.3, 1.0]
])
weights = np.array([
    [0.2, 0.2, 0.6]
])
p_grade = squad @ weights.T
p_grade

array([[0.7 ],
       [0.82],
       [0.72]])